import json

CURRENT_POLICY_VERSION = 4

ALLOWED_CSS_PROPERTIES = {
    "position",
    "top",
    "right",
    "bottom",
    "left",
    "opacity",
    "z-index",
    "transform",
    "font-weight",
    "font-family",
    "font-size",
    "line-height",
    "white-space",
    "content",
    "color",
    "background-color",
    "background",
    "background-image",
    "background-repeat",
    "background-position",
    "background-size",
    "background-attachment",
    "margin",
    "padding",
    "border",
    "border-radius",
    "width",
    "height",
    "min-width",
    "min-height",
    "max-width",
    "max-height",
    "display",
    "float",
    "overflow",
    "text-align",
    "cursor",
    "outline",
    "outline-offset",
    "width",
    "height",
    "box-shadow",
    "filter",
}

allowed_tags = [
    "b",
    "i",
    "u",
    "a",
    "pre",
    "code",
    "br",
    "p",
    "div",
    "span",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "style",
    "img",
    "hr",
    "button",
    "input",
    "textarea",
    "select",
    "option",
    "form",
    "strong",
    "em",
    "bold",
    "italic",
    "ul",
    "li",
    "s",
    "small",
    "table",
    "tr",
    "td",
    "th",
    "thead",
    "tbody",
    "tfoot",
    "caption",
    "col",
    "colgroup",
    "row",
    "rowgroup",
    "center",
    "marquee",
]

allowed_attributes = {
    "a": ["href", "title", "target", "style", "class", "id"],
    "p": ["href", "title", "target", "style", "class", "id"],
    "b": ["href", "title", "target", "style", "class", "id"],
    "bold": ["href", "title", "target", "style", "class", "id"],
    "i": ["href", "title", "target", "style", "class", "id"],
    "italic": ["href", "title", "target", "style", "class", "id"],
    "img": ["src", "alt", "title", "style", "class", "id", "width", "height"],
    "div": ["style", "class", "id"],
    "span": ["style", "class", "id"],
    "style": [],
    "hr": ["style", "class", "id"],
    "button": ["type", "style", "class", "id"],
    "input": ["type", "style", "class", "id"],
    "textarea": ["style", "class", "id"],
    "select": ["style", "class", "id"],
    "option": ["style", "class", "id"],
    "form": ["style", "class", "id", "action", "method", "enctype"],
    "table": ["style", "class", "id"],
    "th": ["style", "class", "id"],
    "td": ["style", "class", "id"],
    "tr": ["style", "class", "id"],
    "col": ["style", "class", "id"],
    "colgroup": ["style", "class", "id"],
    "row": ["style", "class", "id"],
    "rowgroup": ["style", "class", "id"],
    "rowspan": ["style", "class", "id"],
    "colspan": ["style", "class", "id"],
    "align": ["style", "class", "id"],
    "valign": ["style", "class", "id"],
    "border": ["style", "class", "id"],
    "cellpadding": ["style", "class", "id"],
    "cellspacing": ["style", "class", "id"],
    "frame": ["style", "class", "id"],
    "rules": ["style", "class", "id"],
    "summary": ["style", "class", "id"],
    "width": ["style", "class", "id"],
    "height": ["style", "class", "id"],
    "display": ["style", "class", "id"],
    "text-align": ["style", "class", "id"],
    "body": ["style", "class", "id"],
    "center": ["style", "class", "id"],
    "marquee": ["href", "title", "target", "style", "class", "id"],
    "h1": ["style", "class", "id"],
    "h2": ["style", "class", "id"],
    "h3": ["style", "class", "id"],
    "h4": ["style", "class", "id"],
    "h5": ["style", "class", "id"],
    "h6": ["style", "class", "id"],
    "details": ["style", "class", "id"],
}


with open("banned_urls.json", "r") as f:
    BANNED_URLS = set(json.load(f))
